# Generated by Django 2.2 on 2020-02-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200213_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navigation',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
