# Generated by Django 2.2 on 2020-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200216_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
