# Generated by Django 2.2 on 2020-02-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200216_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='summary',
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
