# Generated by Django 2.2 on 2020-02-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200216_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tags',
        ),
    ]
