# Generated by Django 2.2 on 2020-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='greeting',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
