# Generated by Django 2.2 on 2020-02-16 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_config_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='permalink',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$', 'Only alphanumeric, hyphen and underscore characters are allowed (no spaces).')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='permalink',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$', 'Only alphanumeric, hyphen and underscore characters are allowed (no spaces).')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='permalink',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$', 'Only alphanumeric, hyphen and underscore characters are allowed (no spaces).')]),
        ),
    ]
