# Generated by Django 2.2 on 2020-02-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200216_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
